# Generated by Django 6.0.3 on 2026-03-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomerDebt',
        ),
        migrations.DeleteModel(
            name='ExportLog',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseTransaction',
        ),
    ]
