# Generated by Django 6.0.4 on 2026-04-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_add_sales_order_to_export_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportreceipt',
            name='sales_order',
        ),
    ]
