# Generated by Django 6.0.3 on 2026-04-02 05:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0002_remove_exportlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='customerdebt',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='customerdebt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdebt',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='order.salesorder'),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sales_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('WAITING', 'Chờ lấy hàng'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='CONFIRMED', max_length=15),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sales_items', to='product.product')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseTransaction',
        ),
    ]
